#!/usr/bin/env bash
# Configure an Ubuntu server so localhost resolves to 127.0.0.2
# and facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new

sed -i -e 's/127.0.0.2/27.0.0.1/' ~/hosts.new
sed -i -e '2i8.8.8.8 facebook.com' ~/hosts.new

cp -f ~/hosts.new /etc/hosts
